### ISSUE TITLE
Downsampling is missing

### ISSUE THREAD

**Issue by a-maumau** [dazhangyu123/OCL#1]
Hi, I was interested in you work and I tried to run this code, but I get CUDA out of memory error as following:
```sh
neg_loss = ((output_s_[0].T @ output_s_[0]).mean() + (output_s_[1].T @ output_s_[1]).mean()) / naug

RuntimeError: CUDA out of memory. Tried to allocate 1024.00 GiB (GPU 0; 10.76 GiB total capacity; 7.68 GiB already allocated; 101.25
MiB free; 9.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
```

The shape of output from the model is `[2, 19, 524288]`, so it requires `(524288*524288*4)/(1024*1024*1024) = 1024 GB` and this make sense.

in the paper, you mentioned
> downsample the original output resolution of 1024 × 512 by a factor of 8 to a map with a resolution of 128 × 64 before performing the calculation Eq. 5.

There is no downsample part in current code.
Is it OK to just downsample by `torch.nn.functional.interpolate`?

**Comment by dazhangyu123** [comment]
I just use simple solution like this
```
output_s_ = output_s_norm[:,:,::self.downsampling,::self.downsampling].view(naug, c, -1)
```
please check the updated [evalute.py](https://github.com/dazhangyu123/OCL/blob/main/evaluate.py).

**Comment by a-maumau** [comment]
thank you so much for the fast response.
I will try it.
